---
- name: Setup octavia
  hosts: deployment_controller
  any_errors_fatal: true
  tasks:
    - name: Setup Octavia
      shell: |
        #!/bin/bash

        set -xe

        # source venv
        cd workspace
        source kolla-venv/bin/activate

        CONFIG_DIR=$(pwd)/etc/kolla

        # source admin rc
        . $CONFIG_DIR/admin-openrc.sh

        image=octavia-amphora-haproxy-{{ openstack_release }}

        rm -f $image.qcow2.CHECKSUM*
        
        openstack image list -f value | grep -i amphora || (
          wget https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/openstack-octavia-amphora-image/$image.qcow2
          apt install -y qemu-utils
          qemu-img convert $image.qcow2 $image.raw
          openstack image create $image \
            --progress \
            --container-format bare \
            --disk-format raw \
            --private \
            --tag amphora \
            --file $image.raw \
            --property hw_architecture='x86_64' \
            --property hw_rng_model=virtio \
            --project service
          rm -f $image.qcow2 $image.raw
        )

        lb_mgmt_router_external_gatway_ip={{ openstack_amphora_network.router_external_ip }}

        # create octavia management subnet
        openstack subnet show lb-mgmt-subnet || openstack subnet create lb-mgmt-subnet \
                                                --network lb-mgmt-net \
                                                --subnet-range {{ openstack_amphora_network.cidr }} \
                                                --allocation-pool start={{ openstack_amphora_network.allocation_start }},end={{ openstack_amphora_network.allocation_end }}

        # set gateway on octavia management subnet
        openstack subnet set --gateway {{ openstack_amphora_network.gateway_ip }} lb-mgmt-subnet

        # create another (internal) provider subnet to connect to octavia subnet
        openstack subnet show lb-mgmt-provider-subnet || openstack subnet create --no-dhcp --allocation-pool start={{ openstack_octavia_provider_network.allocation_start }},end={{ openstack_octavia_provider_network.allocation_end }} --network public1 --subnet-range {{ openstack_octavia_provider_network.cidr }} lb-mgmt-provider-subnet

        # create router and to make it reachable from octavia worker
        openstack router show lb-mgmt-router || (openstack router create lb-mgmt-router && openstack router add subnet lb-mgmt-router lb-mgmt-subnet)
        openstack router set --disable-snat --external-gateway public1 --fixed-ip subnet=lb-mgmt-provider-subnet,ip-address=$lb_mgmt_router_external_gatway_ip lb-mgmt-router
      args:
        chdir: "{{ playbook_dir }}/../.."
        executable: /bin/bash

- name: Setup octavia routes
  hosts: deployment_nodes
  any_errors_fatal: true
  tasks:
    - name: Setup Octavia
      shell: |
        service=octavia-mgmt-route.service
        unit_file=/etc/systemd/system/$service

        cat > $unit_file <<EOF
        [Unit]
        Description=Add static route for octavia mgmt network
        After=network.target

        [Service]
        Type=oneshot
        ExecStart=/bin/bash -c 'ip r | grep -q ^{{ openstack_amphora_network.cidr }} || ip r add {{ openstack_amphora_network.cidr }} via {{ openstack_amphora_network.router_external_ip }}'

        [Install]
        WantedBy=default.target
        EOF

        systemctl daemon-reload
        systemctl enable $service
        systemctl start $service
        
- name: Test octavia
  hosts: deployment_controller
  any_errors_fatal: true
  tasks:
    - name: Create test loadbalancer and check status
      shell: |
        #!/bin/bash

        set -xe

        # source venv
        cd workspace
        source kolla-venv/bin/activate

        CONFIG_DIR=$(pwd)/etc/kolla

        # source admin rc
        . $CONFIG_DIR/admin-openrc.sh

        suffix=$RANDOM
        openstack loadbalancer show lb-$suffix || openstack loadbalancer create --name lb-$suffix --vip-network-id demo-net

        sleep 60

        timeout_seconds=300
        sleep_time=5
        ready_status=ACTIVE
        wip_status=PENDING_CREATE
        time=0
        while true; do
          status=$(openstack loadbalancer show lb-$suffix -f value -c provisioning_status)
          if [[ $time -gt $timeout_seconds ]]; then
            echo Timeout reached - exiting
            exit 1
          elif echo $status | grep -q $ready_status; then
            echo Now available
            break
          elif echo $status | grep -qv $wip_status ; then
            echo Unexpected status
            exit 1
          fi
          time=$(( $time + $sleep_time ))
          sleep $sleep_time
        done

      args:
        chdir: "{{ playbook_dir }}/../.."
        executable: /bin/bash
