---
all:

  # hosts and hostvars and all shared vars
  hosts:
  
    aio:
      ansible_host: "{{ lookup('ansible.builtin.pipe', 'hostname -I | cut -d \" \" -f 1') }}"
      inventory_index: 1
      ansible_connection: local

  vars:
    
    last_ip_octet: "{{ inventory_index + 10 }}"

    vpn_ip: "10.84.0.{{ last_ip_octet }}/24"
    vpn_interface: vpn0
    vpn_port: 7000

    network_primary_interface: vpn0

    network_openstack_mgmt_ip: "10.0.10.{{ last_ip_octet }}/24"
    network_ceph_public_ip: "10.0.50.{{ last_ip_octet }}/24"
    network_ceph_cluster_ip: "10.0.60.{{ last_ip_octet }}/24" 

    network_netplan_overrides_file:
      network:
        version: 2
        renderer: networkd
        ethernets:
          vpn0:
            addresses:
              - "{{ vpn_ip }}"
        bridges:
          br0:
            interfaces: []
            addresses: [192.168.150.1/24]  
        vlans:
          # openstack management vlan
          openstack_mgmt:
            id: 10
            link: "{{ network_primary_interface }}"
            addresses: 
              - "{{ network_openstack_mgmt_ip }}"
          # ceph public vlan
          ceph_public:
            id: 50
            link: "{{ network_primary_interface }}"
            addresses:
              - "{{ network_ceph_public_ip }}"
          # ceph cluster vlan
          ceph_cluster:
            id: 60
            link: "{{ network_primary_interface }}"
            addresses:
              - "{{ network_ceph_cluster_ip }}"

    network_create_veth_pair: true
    network_add_routes_to_deployment_controller: false
    network_masquerade_vlans: true

    network_primary_gateway_ip: "{{ lookup('ansible.builtin.pipe', 'ip route | grep \"^default\" | head -n 1 | grep -o \"via .*\" | cut -d \" \" -f 2') }}"
    network_primary_interface: "{{ lookup('ansible.builtin.pipe', 'ip route | grep \"^default\" | head -n 1 | grep -o \"dev .*\" | cut -d \" \" -f 2') }}"    

    network_provider_gateway_ip: 192.168.150.1/24

    network_provider_gateway_keepalived_interface: br0
    network_provider_gateway_keepalived_vip: 192.168.150.2

    storage_create_loop_devices: true
    storage_loop_device_size_gb: 30
    storage_ceph_osd_devices:
      - /dev/vg-0/lv-0
      - /dev/vg-1/lv-1
      - /dev/vg-2/lv-2
    storage_ceph_default_pool_size: 1
    storage_ceph_default_min_pool_size: "{{ storage_ceph_default_pool_size }}"
    
    openstack_release: 2024.1
    openstack_network_interface: openstack_mgmt
    openstack_neutron_external_interface: veth0
    openstack_kolla_internal_vip_address: 10.0.10.100
    openstack_designate_forwarders_first_address: 8.8.8.8
    openstack_designate_forwarders_second_address: 8.8.4.4
    openstack_ceph_rgw_hosts: 
      - host: "{{ lookup('ansible.builtin.pipe', 'hostname') }}"
        ip: "{{ lookup('ansible.builtin.pipe', 'ip --json address show ceph_public | jq -r .[0].addr_info[0].local') }}"
        port: 6780
    openstack_worker_count: 1

    openstack_public_network:
      cidr: 192.168.150.0/24
      gateway_ip: 192.168.150.2
      allocation_start: 192.168.150.100
      allocation_end: 192.168.150.200

    openstack_amphora_network:
      cidr: 10.1.0.0/24
      gateway_ip: 10.1.0.1
      allocation_start: 10.1.0.40
      allocation_end: 10.1.0.254
      router_external_ip: 192.168.150.11

  # groups and group vars
  children:
    deployment_controller:
      hosts:
        aio:
    deployment_nodes:
      hosts:
        aio:
