---
# Prereqs:
# - Ensure passwordless ssh access
# - Configure interface with static ip
# - If not dev, configure devices

- name: Set up devices
  hosts: deployment_nodes
  any_errors_fatal: true
  tasks:
    - name: Ensure docker.io is not installed
      apt:
        name: docker.io
        state: absent
        purge: yes

    - name: Install prereqs
      apt:
        name:
          - dnsutils
          - net-tools
          - lvm2
          - openssh-server
          - bridge-utils
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
          - net-tools
          - traceroute
          - vim
          - jq
          - watchman
          - cifs-utils
        update_cache: yes
        cache_valid_time: 3600

    - name: Download docker install script
      command: curl -fsSL https://get.docker.com -o /root/get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Install docker
      command: sh /root/get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Overwrite docker source
      copy:
        dest: /etc/apt/sources.list.d/docker.sources
        content: |
          # Ansible managed

          Types: deb
          URIs: https://download.docker.com/linux/ubuntu
          Suites: jammy
          Components: stable
          Signed-by: /etc/apt/keyrings/docker.asc

    - name: Ensure docker apt key is imported
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Enable docker api over tcp
      shell: |
        mkdir -p /etc/systemd/system/docker.service.d
        cat > /etc/systemd/system/docker.service.d/override.conf <<EOF
        [Service]
        ExecStart=
        ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375 --containerd=/run/containerd/containerd.sock
        EOF
      args:
        creates: /etc/systemd/system/docker.service.d/override.conf
      register: reconfigure_docker

    - name: Enable docker service
      systemd:
        name: docker.service
        state: restarted
        enabled: yes
        daemon_reload: yes
      when: reconfigure_docker.changed

    - name: Ensure docker doesn't set policy to DROP (one time)
      command: iptables --policy FORWARD ACCEPT

    - name: Configure hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Add hosts on deployment controller
      blockinfile:
        state: present
        dest: /etc/hosts
        content: |
          {% for host in groups['deployment_nodes'] %}
          {{ hostvars[host].network_openstack_mgmt_ip | ansible.netcommon.ipaddr('address') }} {{ host }}
          {% endfor %}
      delegate_to: "{{ groups['deployment_controller'][0] }}"
      when: groups['deployment_controller'][0] not in groups['deployment_nodes']
      run_once: true

      # Needed to be added before cephadm deployment
      # Kolla ansible prepare does the same thing
      # Addin the mark "# BEGIN ANSIBLE..." so that duplicates aren't added later :)
    - name: Configure hosts on deployment nodes
      copy: 
        dest: /etc/hosts
        content: |
          127.0.0.1 localhost

          # BEGIN ANSIBLE GENERATED HOSTS
          {% for host in groups['deployment_nodes'] %}
          {{ hostvars[host].network_openstack_mgmt_ip | ansible.netcommon.ipaddr('address') }} {{ host }}
          {% endfor %}
          # END ANSIBLE GENERATED HOSTS

    - name: Add netplan overrides file
      copy:
        dest: /etc/netplan/55-overrides.yaml
        mode: 0600
        content: "{{ network_netplan_overrides_file | to_nice_yaml }}"
      when: network_netplan_overrides_file | length > 0
      register: netplan_config_0

    - name: netplan apply
      command: netplan apply
      when: netplan_config_0.changed | default(false)

    - name: Stop and disable NetworkManager
      systemd:
        name: NetworkManager.service
        state: stopped
        enabled: no
      failed_when: false

    - sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - sysctl:
        name: fs.inotify.max_user_instances
        value: '512'
        sysctl_set: yes
        state: present
        reload: yes

    - name: Run script to setup veth pair
      script: "{{ playbook_dir }}/../scripts/devices/veth_pair.sh"
      when: network_create_veth_pair

    # when running in development using neutron_ext vlan
    - name: Run script to masquerade vlans when exiting primary interface
      script: "{{ playbook_dir }}/../scripts/devices/masquerade.sh"
      when: network_masquerade_vlans

    - name: Configure additional routes in main routing table
      shell: |
        cat > /etc/systemd/system/network_create_routes.service <<EOF
        [Unit]
        Description=Network routes for table main
        After=network.target

        [Service]
        {% for route in network_extra_routes_main_table.routes %}
        ExecStart=/bin/bash -c "ip route show table main | grep -q \"{{ route }}\" || ip route add {{ route }} table main"
        {% endfor %}
        Type=oneshot

        [Install]
        WantedBy=default.target
        RequiredBy=network.target
        EOF

        systemctl daemon-reload
        systemctl restart network_create_routes.service
        systemctl enable network_create_routes.service
      when:
        - network_extra_routes_main_table is defined
        - network_extra_routes_main_table.routes is defined
        - network_extra_routes_main_table.routes | length > 0
        

    - name: Configure additional route tables
      environment:
        table: "{{ item.table }}"
        network_cidr: "{{ item.network_cidr }}"
      shell: |
        cat > /etc/systemd/system/network_create_route_table_$table.service <<EOF
        [Unit]
        Description=Network route table $table for $network_cidr
        After=network.target

        [Service]
        ExecStart=/bin/bash -c "grep -q \"1 $table\" /etc/iproute2/rt_tables || ( echo \"1 $table\" | tee -a /etc/iproute2/rt_tables )"
        ExecStart=/bin/bash -c "ip rule list | grep -q \"from $network_cidr\" || ip rule add from $network_cidr lookup $table"
        ExecStart=/bin/bash -c "ip rule list | grep -q \"to $network_cidr\" || ip rule add to $network_cidr lookup $table"
        {% for route in item.routes %}
        ExecStart=/bin/bash -c "ip route show table $table | grep -q \"{{ route }}\" || ip route add {{ route }} table $table"
        {% endfor %}
        Type=oneshot

        [Install]
        WantedBy=default.target
        RequiredBy=network.target
        EOF

        systemctl daemon-reload
        systemctl restart network_create_route_table_$table.service
        systemctl enable network_create_route_table_$table.service
      loop: "{{ network_extra_route_tables | default([]) }}"

    # DO WE REALLY NEED THIS, IF WE USE VPN?
    - name: Configure network routes on deployment controller
      script: "{{ playbook_dir }}/../scripts/devices/configure_routes.sh"
      environment:
        OPENSTACK_MGMT_NET: "{{ network_openstack_mgmt_ip | ansible.netcommon.ipaddr('network/prefix') }}"
        CEPH_PUBLIC_NET: "{{ network_ceph_public_ip | ansible.netcommon.ipaddr('network/prefix') }}"
        NETWORK_PROVIDER_NET: "{{ network_provider_gateway_ip | ansible.netcommon.ipaddr('network/prefix') }}"
        NETWORK_PRIMARY_GATEWAY_IP: "{{ network_primary_gateway_ip | ansible.netcommon.ipaddr('address') }}"
        NETWORK_PROVIDER_GATEWAY_IP: "{{ network_provider_gateway_ip | ansible.netcommon.ipaddr('address') }}"
      when: network_add_routes_to_deployment_controller | default(false)
      delegate_to: "{{ groups['deployment_controller'][0] }}"
      run_once: true

    - name: Create cni directory for Zun
      command: mkdir -p /opt/cni/bin/

    #- name: Run internet connectivity script
    #  script: "{{ playbook_dir }}/../scripts/devices/revive_internet.sh {{ network_default_gateway_interface }}"

    - name: Configure loop devices
      script: "{{ playbook_dir }}/../scripts/devices/loop.sh"
      environment:
        LOOP_DEVICE_SIZE_GB: "{{ storage_loop_device_size_gb }}"
      when: storage_create_loop_devices
      

- name: Remove internet connectivity script and destroy loop devices
  hosts: deployment_nodes
  any_errors_fatal: true
  tags:
    - destroy
    - never
  tasks:
    - name: Destroy devices
      script: "{{ playbook_dir }}/../scripts/devices/destroy.sh"
      when: storage_create_loop_devices
