- name: Set up devices
  hosts: deployment_nodes
  any_errors_fatal: true
  tasks:
    - name: Ensure docker.io is not installed
      apt:
        name: docker.io
        state: absent
        purge: yes

    - name: Create docker directory
      command: mkdir -p /etc/docker
      args:
        creates: /etc/docker

    - name: Check if docker daemon.json exists
      stat:
        path: /etc/docker/daemon.json
      register: docker_daemon_json

    - name: Add options to docker daemon.json
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
              "bridge": "none",
              "ip-forward": false,
              "ip-forward-no-drop": true,
              "iptables": false,
              "live-restore": true,
              "log-opts": {
                  "max-file": "5",
                  "max-size": "50m"
              }
          }
      when: not docker_daemon_json.stat.exists
      register: docker_daemon_json_configured

    - name: Overwrite docker source
      copy:
        dest: /etc/apt/sources.list.d/docker.sources
        content: |
          # Ansible managed

          Types: deb
          URIs: https://download.docker.com/linux/ubuntu
          Suites: jammy
          Components: stable
          Signed-by: /etc/apt/keyrings/docker.asc

    - name: Download docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc && chmod a+r /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.asc

    - name: Install docker
      apt:
        package:
          - docker-ce 
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
      register: docker_installed

    - name: Ensure docker service is started and enabled
      systemd:
        name: docker
        state: restarted
        enabled: yes
      when: docker_installed.changed or docker_daemon_json_configured.changed

    - name: Enable docker api over tcp
      shell: |
        mkdir -p /etc/systemd/system/docker.service.d
        cat > /etc/systemd/system/docker.service.d/override.conf <<EOF
        [Service]
        ExecStart=
        ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375 --containerd=/run/containerd/containerd.sock
        EOF
      args:
        creates: /etc/systemd/system/docker.service.d/override.conf
      register: reconfigure_docker

    - name: Enable docker service
      systemd:
        name: docker.service
        state: restarted
        enabled: yes
        daemon_reload: yes
      when: reconfigure_docker.changed
